language: java
jdk:
  - openjdk6
before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - cd ..
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar -vzxf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # only update the sdk for the tools and platform-tools (1,2) and whatever api level
  # you are building for android (run "android list sdk" to get the full list. 9 = 2.3.3 or API level 10
  - echo y | android update sdk --filter 1,2,8 --no-ui --force
  - cd ead
