language: java
jdk:
  - openjdk6
before_install:
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null; fi
  - cd ..
  - wget http://dl.google.com/android/android-sdk_r22.3-linux.tgz
  - tar -vzxf android-sdk_r22.3-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # Install required Android SDK components
  # you are building for android (run "android list sdk -a -e" to get the full list. android-10 = 2.3.3 or API level 10
  - echo y | android update sdk --filter tools,platform-tools,build-tools-19.0.3,android-19,android-15,android-10 --no-ui --all
  - cd ead
